"""Initial migration.

Revision ID: d0c7b8e4b57c
Revises: 
Create Date: 2022-11-08 17:00:02.151921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c7b8e4b57c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('ssn', sa.String(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('annual_income', sa.Float(), nullable=True),
    sa.Column('monthly_inhand_salary', sa.Float(), nullable=True),
    sa.Column('num_bank_accounts', sa.Integer(), nullable=True),
    sa.Column('num_credit_card', sa.Integer(), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('num_of_loan', sa.Integer(), nullable=True),
    sa.Column('type_of_loan', sa.String(), nullable=True),
    sa.Column('delay_from_due_date', sa.Integer(), nullable=True),
    sa.Column('num_of_delayed_payment', sa.Integer(), nullable=True),
    sa.Column('changed_credit_limit', sa.Float(), nullable=True),
    sa.Column('num_credit_inquiries', sa.Integer(), nullable=True),
    sa.Column('credit_mix', sa.String(), nullable=True),
    sa.Column('outstanding_debt', sa.Float(), nullable=True),
    sa.Column('credit_utilization_ratio', sa.Float(), nullable=True),
    sa.Column('credit_history_age', sa.Integer(), nullable=True),
    sa.Column('payment_of_min_amount', sa.String(), nullable=True),
    sa.Column('total_emi_per_month', sa.Float(), nullable=True),
    sa.Column('amount_invested_monthly', sa.Float(), nullable=True),
    sa.Column('payment_behaviour', sa.String(), nullable=True),
    sa.Column('monthly_balance', sa.Float(), nullable=True),
    sa.Column('credit_score', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_data')
    op.drop_table('eda_results')
    op.drop_table('selected_features')
    op.drop_table('predictions')
    # ### end Alembic commands ###